import type { Area } from '@/types';

export const AREAS_WITH_SUBAREAS: Area[] = [
  // 🌱 TERRA (10 áreas)
  {
    id: 'area-saude',
    name: 'Exercício Físico',
    description: 'Treinamento, condicionamento e práticas de movimento',
    elementId: 'terra',
    color: '#4CAF50',
    parentId: null,
    subareas: [
      { id: 'sub-saude-musculacao', name: 'Musculação', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-calistenia', name: 'Calistenia', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-yoga', name: 'Yoga', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-pilates', name: 'Pilates', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-corrida', name: 'Corrida', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-natacao', name: 'Natação', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-artes-marciais', name: 'Artes marciais', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-esportes-coletivos', name: 'Esportes coletivos', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-alongamento', name: 'Alongamento', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisioterapia', name: 'Fisioterapia', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-mobilidade', name: 'Mobilidade', description: '', elementId: 'terra', color: '#4CAF50', parentId: 'area-saude', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-saude-fisica',
    name: 'Saúde Física',
    description: 'Cuidados clínicos e prevenção para o corpo',
    elementId: 'terra',
    color: '#43A047',
    parentId: null,
    subareas: [
      { id: 'sub-saude-fisica-checkup', name: 'Check-ups médicos', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisica-bucal', name: 'Saúde bucal (dentes)', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisica-pele', name: 'Saúde da pele', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisica-coluna', name: 'Coluna e postura', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisica-visao', name: 'Visão', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisica-hormonal', name: 'Saúde hormonal', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-saude-fisica-exames', name: 'Exames de rotina', description: '', elementId: 'terra', color: '#43A047', parentId: 'area-saude-fisica', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-nutricao',
    name: 'Nutrição',
    description: 'Alimentação saudável e hábitos alimentares',
    elementId: 'terra',
    color: '#66BB6A',
    parentId: null,
    subareas: [
      { id: 'sub-nutricao-alimentacao-saudavel', name: 'Alimentação saudável', description: '', elementId: 'terra', color: '#66BB6A', parentId: 'area-nutricao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-nutricao-hidratacao', name: 'Hidratação', description: '', elementId: 'terra', color: '#66BB6A', parentId: 'area-nutricao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-nutricao-planejamento', name: 'Planejamento alimentar', description: '', elementId: 'terra', color: '#66BB6A', parentId: 'area-nutricao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-nutricao-suplementacao', name: 'Suplementação', description: '', elementId: 'terra', color: '#66BB6A', parentId: 'area-nutricao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-nutricao-dietas', name: 'Dietas específicas', description: '', elementId: 'terra', color: '#66BB6A', parentId: 'area-nutricao', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-sono',
    name: 'Sono & Recuperação',
    description: 'Qualidade do sono e momentos de descanso',
    elementId: 'terra',
    color: '#8DAA91',
    parentId: null,
    subareas: [
      { id: 'sub-sono-rotina', name: 'Rotina de sono', description: '', elementId: 'terra', color: '#8DAA91', parentId: 'area-sono', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-sono-higiene', name: 'Higiene do sono', description: '', elementId: 'terra', color: '#8DAA91', parentId: 'area-sono', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-sono-descanso-ativo', name: 'Descanso ativo', description: '', elementId: 'terra', color: '#8DAA91', parentId: 'area-sono', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-sono-energia', name: 'Energia & Vitalidade', description: '', elementId: 'terra', color: '#8DAA91', parentId: 'area-sono', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-financas',
    name: 'Finanças',
    description: 'Orçamento, investimentos e planejamento financeiro',
    elementId: 'terra',
    color: '#2E7D32',
    parentId: null,
    subareas: [
      { id: 'sub-financas-orcamento', name: 'Orçamento', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-financas-controle-gastos', name: 'Controle de gastos', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-financas-investimentos', name: 'Investimentos', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-financas-reserva-emergencia', name: 'Reserva de emergência', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-financas-aposentadoria', name: 'Aposentadoria', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-financas-renda-extra', name: 'Renda extra', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-financas-impostos', name: 'Impostos', description: '', elementId: 'terra', color: '#2E7D32', parentId: 'area-financas', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-casa',
    name: 'Casa & Ambiente',
    description: 'Organização do espaço, limpeza e decoração',
    elementId: 'terra',
    color: '#5E8C61',
    parentId: null,
    subareas: [
      { id: 'sub-casa-limpeza', name: 'Limpeza', description: '', elementId: 'terra', color: '#5E8C61', parentId: 'area-casa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-casa-organizacao', name: 'Organização', description: '', elementId: 'terra', color: '#5E8C61', parentId: 'area-casa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-casa-reforma', name: 'Reforma', description: '', elementId: 'terra', color: '#5E8C61', parentId: 'area-casa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-casa-decoracao', name: 'Decoração', description: '', elementId: 'terra', color: '#5E8C61', parentId: 'area-casa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-casa-jardinagem', name: 'Jardinagem', description: '', elementId: 'terra', color: '#5E8C61', parentId: 'area-casa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-casa-manutencao', name: 'Manutenção', description: '', elementId: 'terra', color: '#5E8C61', parentId: 'area-casa', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-rotina',
    name: 'Disciplina & Rotina',
    description: 'Hábitos diários e estrutura de tempo',
    elementId: 'terra',
    color: '#556B2F',
    parentId: null,
    subareas: [
      { id: 'sub-rotina-matinal', name: 'Rotina matinal', description: '', elementId: 'terra', color: '#556B2F', parentId: 'area-rotina', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-rotina-noturna', name: 'Rotina noturna', description: '', elementId: 'terra', color: '#556B2F', parentId: 'area-rotina', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-rotina-organizacao-diaria', name: 'Organização diária', description: '', elementId: 'terra', color: '#556B2F', parentId: 'area-rotina', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-rotina-construcao-habitos', name: 'Construção de hábitos', description: '', elementId: 'terra', color: '#556B2F', parentId: 'area-rotina', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-logistica',
    name: 'Logística',
    description: 'Transporte, viagens e organização prática',
    elementId: 'terra',
    color: '#6B8E6B',
    parentId: null,
    subareas: [
      { id: 'sub-logistica-documentacao', name: 'Documentação', description: '', elementId: 'terra', color: '#6B8E6B', parentId: 'area-logistica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-logistica-compras', name: 'Compras', description: '', elementId: 'terra', color: '#6B8E6B', parentId: 'area-logistica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-logistica-transporte', name: 'Transporte', description: '', elementId: 'terra', color: '#6B8E6B', parentId: 'area-logistica', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-logistica-planejamento', name: 'Planejamento doméstico', description: '', elementId: 'terra', color: '#6B8E6B', parentId: 'area-logistica', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-mobilidade',
    name: 'Mobilidade',
    description: 'Flexibilidade, alongamento e movimento',
    elementId: 'terra',
    color: '#7CB342',
    parentId: null,
    subareas: [],
    isUserSelected: false,
    isCustom: false,
  },

  // 🔥 FOGO (8 áreas)
  {
    id: 'area-carreira',
    name: 'Carreira',
    description: 'Desenvolvimento profissional e crescimento na carreira',
    elementId: 'fogo',
    color: '#F25C05',
    parentId: null,
    subareas: [
      { id: 'sub-carreira-desenvolvimento', name: 'Desenvolvimento profissional', description: '', elementId: 'fogo', color: '#F25C05', parentId: 'area-carreira', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-carreira-promocao', name: 'Promoção', description: '', elementId: 'fogo', color: '#F25C05', parentId: 'area-carreira', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-carreira-networking', name: 'Networking', description: '', elementId: 'fogo', color: '#F25C05', parentId: 'area-carreira', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-carreira-desempenho', name: 'Metas de desempenho', description: '', elementId: 'fogo', color: '#F25C05', parentId: 'area-carreira', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-profissao',
    name: 'Profissão',
    description: 'Especializações e projetos profissionais',
    elementId: 'fogo',
    color: '#D9480F',
    parentId: null,
    subareas: [
      { id: 'sub-profissao-especializacoes', name: 'Especializações', description: '', elementId: 'fogo', color: '#D9480F', parentId: 'area-profissao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-profissao-projetos', name: 'Projetos profissionais', description: '', elementId: 'fogo', color: '#D9480F', parentId: 'area-profissao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-profissao-aprendizado', name: 'Aprendizado técnico', description: '', elementId: 'fogo', color: '#D9480F', parentId: 'area-profissao', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-empreendedorismo',
    name: 'Empreendedorismo',
    description: 'Negócios, vendas e estratégia comercial',
    elementId: 'fogo',
    color: '#E85D04',
    parentId: null,
    subareas: [
      { id: 'sub-empreendedorismo-produto', name: 'Produto', description: '', elementId: 'fogo', color: '#E85D04', parentId: 'area-empreendedorismo', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-empreendedorismo-vendas', name: 'Vendas', description: '', elementId: 'fogo', color: '#E85D04', parentId: 'area-empreendedorismo', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-empreendedorismo-marketing', name: 'Marketing', description: '', elementId: 'fogo', color: '#E85D04', parentId: 'area-empreendedorismo', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-empreendedorismo-estrategia', name: 'Estratégia comercial', description: '', elementId: 'fogo', color: '#E85D04', parentId: 'area-empreendedorismo', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-empreendedorismo-lancamentos', name: 'Lançamentos', description: '', elementId: 'fogo', color: '#E85D04', parentId: 'area-empreendedorismo', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-projetos',
    name: 'Projetos Pessoais',
    description: 'Construção de projetos e metas específicas',
    elementId: 'fogo',
    color: '#FF7F11',
    parentId: null,
    subareas: [
      { id: 'sub-projetos-construcao', name: 'Construção de algo novo', description: '', elementId: 'fogo', color: '#FF7F11', parentId: 'area-projetos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-projetos-metas', name: 'Metas específicas', description: '', elementId: 'fogo', color: '#FF7F11', parentId: 'area-projetos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-projetos-desafios', name: 'Desafios', description: '', elementId: 'fogo', color: '#FF7F11', parentId: 'area-projetos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-projetos-lideranca', name: 'Liderança', description: '', elementId: 'fogo', color: '#FF7F11', parentId: 'area-projetos', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-lideranca',
    name: 'Liderança',
    description: 'Gestão de equipe e mentoria',
    elementId: 'fogo',
    color: '#C1121F',
    parentId: null,
    subareas: [
      { id: 'sub-lideranca-gestao-equipe', name: 'Gestão de equipe', description: '', elementId: 'fogo', color: '#C1121F', parentId: 'area-lideranca', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-lideranca-mentoria', name: 'Mentoria', description: '', elementId: 'fogo', color: '#C1121F', parentId: 'area-lideranca', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-lideranca-influencia', name: 'Influência', description: '', elementId: 'fogo', color: '#C1121F', parentId: 'area-lideranca', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-lideranca-oratoria', name: 'Oratória', description: '', elementId: 'fogo', color: '#C1121F', parentId: 'area-lideranca', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-lideranca-performance', name: 'Performance', description: '', elementId: 'fogo', color: '#C1121F', parentId: 'area-lideranca', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-alta-performance',
    name: 'Alta Performance',
    description: 'Excelência e superação de limites',
    elementId: 'fogo',
    color: '#9D0208',
    parentId: null,
    subareas: [
      { id: 'sub-performance-alta-performance', name: 'Alta performance', description: '', elementId: 'fogo', color: '#9D0208', parentId: 'area-alta-performance', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-performance-competicao', name: 'Competição', description: '', elementId: 'fogo', color: '#9D0208', parentId: 'area-alta-performance', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-performance-superacao', name: 'Superação', description: '', elementId: 'fogo', color: '#9D0208', parentId: 'area-alta-performance', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-arte',
    name: 'Arte & Expressão',
    description: 'Criatividade artística e produção artística',
    elementId: 'fogo',
    color: '#E63946',
    parentId: null,
    subareas: [
      { id: 'sub-arte-musica', name: 'Música', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-arte-teatro', name: 'Teatro', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-arte-pintura', name: 'Pintura', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-arte-escrita', name: 'Escrita artística', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-arte-conteudo', name: 'Produção de conteúdo', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-arte-fotografia', name: 'Fotografia', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-arte-danca', name: 'Dança', description: '', elementId: 'fogo', color: '#E63946', parentId: 'area-arte', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-marca-pessoal',
    name: 'Marca Pessoal',
    description: 'Branding pessoal e posicionamento',
    elementId: 'fogo',
    color: '#FF4D6D',
    parentId: null,
    subareas: [
      { id: 'sub-marca-redes-sociais', name: 'Redes sociais', description: '', elementId: 'fogo', color: '#FF4D6D', parentId: 'area-marca-pessoal', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-marca-posicionamento', name: 'Posicionamento', description: '', elementId: 'fogo', color: '#FF4D6D', parentId: 'area-marca-pessoal', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-marca-branding', name: 'Branding pessoal', description: '', elementId: 'fogo', color: '#FF4D6D', parentId: 'area-marca-pessoal', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },

  // 🌊 ÁGUA (6 áreas)
  {
    id: 'area-relacionamentos',
    name: 'Relacionamentos',
    description: 'Conexões interpessoais e vida social',
    elementId: 'agua',
    color: '#0077B6',
    parentId: null,
    subareas: [
      { id: 'sub-relacionamentos-parceiro', name: 'Parceiro(a)', description: '', elementId: 'agua', color: '#0077B6', parentId: 'area-relacionamentos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-relacionamentos-amizades', name: 'Amizades', description: '', elementId: 'agua', color: '#0077B6', parentId: 'area-relacionamentos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-relacionamentos-vida-social', name: 'Vida social', description: '', elementId: 'agua', color: '#0077B6', parentId: 'area-relacionamentos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-relacionamentos-familia', name: 'Família', description: '', elementId: 'agua', color: '#0077B6', parentId: 'area-relacionamentos', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-familia',
    name: 'Família',
    description: 'Relacionamento familiar direito',
    elementId: 'agua',
    color: '#48CAE4',
    parentId: null,
    subareas: [
      { id: 'sub-familia-pais', name: 'Pais', description: '', elementId: 'agua', color: '#48CAE4', parentId: 'area-familia', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-familia-filhos', name: 'Filhos', description: '', elementId: 'agua', color: '#48CAE4', parentId: 'area-familia', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-familia-parentes', name: 'Parentes', description: '', elementId: 'agua', color: '#48CAE4', parentId: 'area-familia', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-familia-animal-estimacao', name: 'Animal de estimação', description: '', elementId: 'agua', color: '#48CAE4', parentId: 'area-familia', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-espiritualidade',
    name: 'Espiritualidade',
    description: 'Práticas espirituais e desenvolvimento interior',
    elementId: 'agua',
    color: '#023E8A',
    parentId: null,
    subareas: [
      { id: 'sub-espiritualidade-meditacao', name: 'Meditação', description: '', elementId: 'agua', color: '#023E8A', parentId: 'area-espiritualidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-espiritualidade-oracao', name: 'Oração', description: '', elementId: 'agua', color: '#023E8A', parentId: 'area-espiritualidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-espiritualidade-ritual', name: 'Ritual', description: '', elementId: 'agua', color: '#023E8A', parentId: 'area-espiritualidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-espiritualidade-magia', name: 'Magia', description: '', elementId: 'agua', color: '#023E8A', parentId: 'area-espiritualidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-espiritualidade-estudo', name: 'Estudo espiritual', description: '', elementId: 'agua', color: '#023E8A', parentId: 'area-espiritualidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-espiritualidade-autoconhecimento', name: 'Autoconhecimento', description: '', elementId: 'agua', color: '#023E8A', parentId: 'area-espiritualidade', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-desenvolvimento-pessoal',
    name: 'Desenvolvimento pessoal',
    description: 'Crescimento pessoal e transformação',
    elementId: 'agua',
    color: '#3A86FF',
    parentId: null,
    subareas: [
      { id: 'sub-desenvolvimento-terapia', name: 'Terapia', description: '', elementId: 'agua', color: '#3A86FF', parentId: 'area-desenvolvimento-pessoal', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-desenvolvimento-journaling', name: 'Journaling', description: '', elementId: 'agua', color: '#3A86FF', parentId: 'area-desenvolvimento-pessoal', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-desenvolvimento-reflexao', name: 'Reflexão', description: '', elementId: 'agua', color: '#3A86FF', parentId: 'area-desenvolvimento-pessoal', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-desenvolvimento-pessoal-geral', name: 'Desenvolvimento pessoal', description: '', elementId: 'agua', color: '#3A86FF', parentId: 'area-desenvolvimento-pessoal', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-emocoes',
    name: 'Emoções & Saúde Mental',
    description: 'Bem-estar emocional e mental',
    elementId: 'agua',
    color: '#00B4D8',
    parentId: null,
    subareas: [
      { id: 'sub-emocoes-regulacao', name: 'Regulação emocional', description: '', elementId: 'agua', color: '#00B4D8', parentId: 'area-emocoes', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-emocoes-autocuidado', name: 'Autocuidado', description: '', elementId: 'agua', color: '#00B4D8', parentId: 'area-emocoes', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-emocoes-mindfulness', name: 'Mindfulness', description: '', elementId: 'agua', color: '#00B4D8', parentId: 'area-emocoes', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-comunidade',
    name: 'Comunidade & Impacto Social',
    description: 'Voluntariado e impacto social',
    elementId: 'agua',
    color: '#0096C7',
    parentId: null,
    subareas: [
      { id: 'sub-comunidade-voluntariado', name: 'Voluntariado', description: '', elementId: 'agua', color: '#0096C7', parentId: 'area-comunidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-comunidade-grupos', name: 'Grupos', description: '', elementId: 'agua', color: '#0096C7', parentId: 'area-comunidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-comunidade-causas', name: 'Causas', description: '', elementId: 'agua', color: '#0096C7', parentId: 'area-comunidade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-comunidade-ativismo', name: 'Ativismo', description: '', elementId: 'agua', color: '#0096C7', parentId: 'area-comunidade', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },

  // 🌬️ AR (7 áreas)
  {
    id: 'area-estudos',
    name: 'Estudos',
    description: 'Educação formal e aprendizado acadêmico',
    elementId: 'ar',
    color: '#90E0EF',
    parentId: null,
    subareas: [
      { id: 'sub-estudos-faculdade', name: 'Faculdade', description: '', elementId: 'ar', color: '#90E0EF', parentId: 'area-estudos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-estudos-cursos', name: 'Cursos', description: '', elementId: 'ar', color: '#90E0EF', parentId: 'area-estudos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-estudos-certificacoes', name: 'Certificações', description: '', elementId: 'ar', color: '#90E0EF', parentId: 'area-estudos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-estudos-pos-graduacao', name: 'Pós-graduação', description: '', elementId: 'ar', color: '#90E0EF', parentId: 'area-estudos', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-estudos-leitura', name: 'Leitura', description: '', elementId: 'ar', color: '#90E0EF', parentId: 'area-estudos', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-leitura',
    name: 'Leitura & Conteúdo',
    description: 'Leitura de livros e consumo de conteúdo',
    elementId: 'ar',
    color: '#8ECAE6',
    parentId: null,
    subareas: [
      { id: 'sub-leitura-livros', name: 'Livros', description: '', elementId: 'ar', color: '#8ECAE6', parentId: 'area-leitura', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-leitura-artigos', name: 'Artigos', description: '', elementId: 'ar', color: '#8ECAE6', parentId: 'area-leitura', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-leitura-comunicacao', name: 'Comunicação', description: '', elementId: 'ar', color: '#8ECAE6', parentId: 'area-leitura', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-comunicacao',
    name: 'Comunicação',
    description: 'Desenvolvimento de habilidades de comunicação',
    elementId: 'ar',
    color: '#219EBC',
    parentId: null,
    subareas: [
      { id: 'sub-comunicacao-escrita', name: 'Escrita', description: '', elementId: 'ar', color: '#219EBC', parentId: 'area-comunicacao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-comunicacao-oratoria', name: 'Oratória', description: '', elementId: 'ar', color: '#219EBC', parentId: 'area-comunicacao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-comunicacao-idiomas', name: 'Idiomas', description: '', elementId: 'ar', color: '#219EBC', parentId: 'area-comunicacao', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-comunicacao-storytelling', name: 'Storytelling', description: '', elementId: 'ar', color: '#219EBC', parentId: 'area-comunicacao', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-tecnologia',
    name: 'Tecnologia',
    description: 'Desenvolvimento de habilidades tecnológicas',
    elementId: 'ar',
    color: '#3A86FF',
    parentId: null,
    subareas: [
      { id: 'sub-tecnologia-programacao', name: 'Programação', description: '', elementId: 'ar', color: '#3A86FF', parentId: 'area-tecnologia', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-tecnologia-ia', name: 'IA', description: '', elementId: 'ar', color: '#3A86FF', parentId: 'area-tecnologia', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-tecnologia-ferramentas', name: 'Ferramentas digitais', description: '', elementId: 'ar', color: '#3A86FF', parentId: 'area-tecnologia', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-tecnologia-automacao', name: 'Automação', description: '', elementId: 'ar', color: '#3A86FF', parentId: 'area-tecnologia', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-pesquisa',
    name: 'Pesquisa & Análise',
    description: 'Investigação e análise crítica',
    elementId: 'ar',
    color: '#5C7AEA',
    parentId: null,
    subareas: [
      { id: 'sub-pesquisa-investigacao', name: 'Investigação', description: '', elementId: 'ar', color: '#5C7AEA', parentId: 'area-pesquisa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-pesquisa-producao-intelectual', name: 'Produção intelectual', description: '', elementId: 'ar', color: '#5C7AEA', parentId: 'area-pesquisa', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-pesquisa-analise-estrategica', name: 'Análise estratégica', description: '', elementId: 'ar', color: '#5C7AEA', parentId: 'area-pesquisa', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-planejamento',
    name: 'Planejamento & Estratégia',
    description: 'Planejamento e desenvolvimento estratégico',
    elementId: 'ar',
    color: '#A8DADC',
    parentId: null,
    subareas: [
      { id: 'sub-planejamento-metas', name: 'Metas', description: '', elementId: 'ar', color: '#A8DADC', parentId: 'area-planejamento', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-planejamento-anual', name: 'Planejamento anual', description: '', elementId: 'ar', color: '#A8DADC', parentId: 'area-planejamento', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-planejamento-estruturacao', name: 'Estruturação de projetos', description: '', elementId: 'ar', color: '#A8DADC', parentId: 'area-planejamento', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
  {
    id: 'area-criatividade',
    name: 'Criatividade Intelectual',
    description: 'Exploração de ideias e criatividade',
    elementId: 'ar',
    color: '#BDE0FE',
    parentId: null,
    subareas: [
      { id: 'sub-criatividade-brainstorm', name: 'Brainstorm', description: '', elementId: 'ar', color: '#BDE0FE', parentId: 'area-criatividade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-criatividade-escrita-criativa', name: 'Escrita criativa', description: '', elementId: 'ar', color: '#BDE0FE', parentId: 'area-criatividade', subareas: [], isUserSelected: false, isCustom: false },
      { id: 'sub-criatividade-desenvolvimento-ideias', name: 'Desenvolvimento de ideias', description: '', elementId: 'ar', color: '#BDE0FE', parentId: 'area-criatividade', subareas: [], isUserSelected: false, isCustom: false },
    ],
    isUserSelected: false,
    isCustom: false,
  },
];
