export type YogaPose = {
  id: string;
  namePt: string;
  nameSanskrit: string;
  family: string;
  focus: string;
  level: 'Iniciante' | 'Intermediário';
  benefits: string[];
  alignment: string[];
  breathing: string;
  contraindications?: string[];
  duration?: string;
  variations?: string[];
};

export const YOGA_POSES: YogaPose[] = [
  {
    id: 'tadasana',
    namePt: 'Postura da Montanha',
    nameSanskrit: 'Tadasana',
    family: 'Posturas em pé',
    focus: 'alinhamento e presença',
    level: 'Iniciante',
    benefits: [
      'Melhora o alinhamento postural',
      'Fortalece as coxas e tornozelos',
      'Cultiva estabilidade mental',
      'Estimula consciência corporal',
    ],
    alignment: [
      'Pés paralelos com dedos espalhados',
      'Peso distribuído uniformemente',
      'Quadris alinhados com ombros',
      'Coroa da cabeça apontando para o céu',
    ],
    breathing: 'Respiração natural e profunda, observando o fluxo de energia',
    duration: '30-60 segundos',
    variations: ['Tadasana com olhos fechados', 'Tadasana com palmas juntas no peito'],
  },
  {
    id: 'vrksasana',
    namePt: 'Postura da Árvore',
    nameSanskrit: 'Vrksasana',
    family: 'Equilíbrio em pé',
    focus: 'equilíbrio e concentração',
    level: 'Iniciante',
    benefits: [
      'Aprimora o equilíbrio e propriocepção',
      'Fortalece pernas e glúteos',
      'Desenvolve foco mental',
      'Melhora a estabilidade emocional',
    ],
    alignment: [
      'Pé de apoio bem enraizado no solo',
      'Outro pé pressionado contra a coxa interna',
      'Quadril aberto para o lado',
      'Mãos em posição de oração ou levantadas',
    ],
    breathing: 'Respiração lenta e profunda, focando no enraizamento',
    duration: '30-45 segundos em cada lado',
    contraindications: ['Pressão arterial baixa recente', 'Tontura'],
    variations: ['Vrksasana com pé em meia altura', 'Vrksasana com braços levantados'],
  },
  {
    id: 'virabhadrasana-ii',
    namePt: 'Guerreiro II',
    nameSanskrit: 'Virabhadrasana II',
    family: 'Posturas em pé',
    focus: 'força de pernas e estabilidade',
    level: 'Iniciante',
    benefits: [
      'Fortalece pernas, glúteos e costas',
      'Melhora resistência e estamina',
      'Abre quadris e ombros',
      'Cultiva coragem e determinação',
    ],
    alignment: [
      'Pés afastados na largura das cadeiras',
      'Pé dianteiro a 90 graus, traseiro a 45 graus',
      'Joelho dianteiro alinhado com tornozelo',
      'Tronco ereto e ombros relaxados',
    ],
    breathing: 'Inspiração enquanto estabiliza, expiração enquanto aprofunda',
    duration: '30-60 segundos em cada lado',
    variations: ['Guerreiro II com braços estendidos', 'Guerreiro II com palmas juntas'],
  },
  {
    id: 'adho-mukha-svanasana',
    namePt: 'Cachorro olhando para baixo',
    nameSanskrit: 'Adho Mukha Svanasana',
    family: 'Transição e força',
    focus: 'cadeia posterior e ombros',
    level: 'Iniciante',
    benefits: [
      'Alonga toda a cadeia posterior do corpo',
      'Fortalece braços e ombros',
      'Relaxa sistema nervoso',
      'Inverte a circulação energética',
    ],
    alignment: [
      'Mãos afastadas na largura dos ombros',
      'Pés afastados na largura dos quadris',
      'Cabeça entre os braços',
      'Coccix apontando para o céu',
    ],
    breathing: 'Inspiração profunda, expiração com alongamento',
    duration: '30-60 segundos',
    variations: ['Com joelhos levemente flexionados', 'Com pés em movimento alternado'],
  },
  {
    id: 'uttanasana',
    namePt: 'Pinça em pé',
    nameSanskrit: 'Uttanasana',
    family: 'Flexões à frente',
    focus: 'alongamento posterior e calma',
    level: 'Iniciante',
    benefits: [
      'Alonga isquiotibiais e coluna vertebral',
      'Reduz estresse e ansiedade',
      'Melhora circulação cerebral',
      'Acalma o sistema nervoso',
    ],
    alignment: [
      'Pés paralelos afastados na largura dos quadris',
      'Dobra a partir dos quadris, não da cintura',
      'Braços pendurados naturalmente',
      'Cabeça e pescoço relaxados',
    ],
    breathing: 'Expiração profunda enquanto desce, inspiração enquanto sobe',
    duration: '1-2 minutos',
    contraindications: ['Pressão alta não controlada', 'Descolamento de retina'],
    variations: ['Uttanasana com mãos segurando os pés', 'Uttanasana dinâmica com movimento'],
  },
  {
    id: 'bhujangasana',
    namePt: 'Cobra',
    nameSanskrit: 'Bhujangasana',
    family: 'Extensões',
    focus: 'mobilidade torácica e abertura de peito',
    level: 'Iniciante',
    benefits: [
      'Fortalece costas e braços',
      'Abre peito e ombros',
      'Melhora postura',
      'Estimula órgãos abdominais',
    ],
    alignment: [
      'Mãos sob os ombros',
      'Cotovelos próximos ao corpo',
      'Ombros afastados das orelhas',
      'Pubis pressionado no chão',
    ],
    breathing: 'Inspiração enquanto levanta o peito, expiração enquanto baixa',
    duration: '15-30 segundos',
    contraindications: ['Síndrome do túnel do carpo', 'Gravidez avançada'],
    variations: ['Cobra baixa', 'Cobra com braços estendidos'],
  },
  {
    id: 'ustrasana',
    namePt: 'Camelo',
    nameSanskrit: 'Ustrasana',
    family: 'Extensões',
    focus: 'abertura de quadris e peitoral',
    level: 'Intermediário',
    benefits: [
      'Abre intensa o peito e abdômen',
      'Alonga flexores de quadril',
      'Fortalece costas',
      'Libera emoções retidas',
    ],
    alignment: [
      'Joelhos afastados na largura dos quadris',
      'Mãos no sacro ou nas solas dos pés',
      'Peito aberto para o céu',
      'Cabeça em posição neutra ou levemente para trás',
    ],
    breathing: 'Inspiração profunda na abertura, expiração na sustentação',
    duration: '15-30 segundos',
    contraindications: ['Pressão alta', 'Problemas na coluna cervical'],
    variations: ['Camelo com uma mão no sacro', 'Camelo preparatório com mãos em blocos'],
  },
  {
    id: 'ardha-matsyendrasana',
    namePt: 'Torção sentada',
    nameSanskrit: 'Ardha Matsyendrasana',
    family: 'Torções',
    focus: 'mobilidade de coluna e respiração',
    level: 'Iniciante',
    benefits: [
      'Massageia órgãos internos',
      'Mobiliza a coluna vertebral',
      'Melhora digestão',
      'Libera tensão na parte superior das costas',
    ],
    alignment: [
      'Coluna alongada na inspiração',
      'Torção aprofunda na expiração',
      'Braço contrário apoiado na coxa oposta',
      'Ombros relaxados para trás',
    ],
    breathing: 'Expiração profunda na torção para maior penetração',
    duration: '30-60 segundos em cada lado',
    contraindications: ['Hérnias discais', 'Gravidez'],
    variations: ['Com perna estendida', 'Com perna flexionada'],
  },
  {
    id: 'eka-pada-rajakapotasana',
    namePt: 'Pombo',
    nameSanskrit: 'Eka Pada Rajakapotasana (prep.)',
    family: 'Abertura de quadris',
    focus: 'glúteos e quadril profundo',
    level: 'Intermediário',
    benefits: [
      'Alonga profundamente glúteos e músculos do quadril',
      'Libera tensão acumulada no quadril',
      'Melhora flexibilidade',
      'Alivia dor nas costas',
    ],
    alignment: [
      'Joelho da frente flexionado',
      'Quadril alinhado',
      'Tronco ereto ou inclinado para frente',
      'Pressão uniforme no chão',
    ],
    breathing: 'Expiração profunda na flexão frontal para aprofundar o alongamento',
    duration: '1-2 minutos em cada lado',
    contraindications: ['Lesão nos joelhos ou quadril'],
    variations: ['Pombo preparatório em quatro apoios', 'Pombo com inclinação frontal'],
  },
  {
    id: 'balasana',
    namePt: 'Postura da Criança',
    nameSanskrit: 'Balasana',
    family: 'Recuperação',
    focus: 'descanso e regulação do sistema nervoso',
    level: 'Iniciante',
    benefits: [
      'Repousa o sistema nervoso',
      'Alonga coluna vertebral e quadril',
      'Acalma mente agitada',
      'Restaura energia',
    ],
    alignment: [
      'Joelhos afastados ou juntos',
      'Testa apoiada no tapete',
      'Braços estendidos ou ao lado do corpo',
      'Respiração lenta e natural',
    ],
    breathing: 'Respiração natural e meditativa',
    duration: '1-5 minutos (quanto mais, melhor)',
    variations: ['Com braços estendidos', 'Com braços ao lado', 'Com pernas juntas'],
  },
  {
    id: 'setu-bandhasana',
    namePt: 'Meia Ponte',
    nameSanskrit: 'Setu Bandhasana',
    family: 'Extensões',
    focus: 'cadeia posterior e estabilidade lombar',
    level: 'Iniciante',
    benefits: [
      'Fortalece glúteos e isquiotibiais',
      'Protege a coluna lombar',
      'Abre peito e ombros',
      'Melhora circulação',
    ],
    alignment: [
      'Pés paralelos afastados na largura dos quadris',
      'Mãos entrelaçadas sob o corpo',
      'Glúteos contraídos na sustentação',
      'Joelhos alinhados com tornozelos',
    ],
    breathing: 'Inspiração enquanto levanta, expiração na sustentação',
    duration: '30-60 segundos',
    contraindications: ['Síndrome do impacto de ombro'],
    variations: ['Com blocos sob o sacro', 'Com perna estendida'],
  },
  {
    id: 'savasana',
    namePt: 'Postura do Cadáver',
    nameSanskrit: 'Savasana',
    family: 'Encerramento',
    focus: 'integração e relaxamento profundo',
    level: 'Iniciante',
    benefits: [
      'Integra todos os benefícios da prática',
      'Reduz estresse e ansiedade profundamente',
      'Restaura energia vital',
      'Conecta mente, corpo e espírito',
    ],
    alignment: [
      'Corpo completamente relaxado',
      'Pés naturalmente afastados',
      'Braços ao lado com palmas abertas',
      'Cabeça em posição neutra',
    ],
    breathing: 'Respiração natural, observação silenciosa',
    duration: '5-15 minutos (mínimo 5)',
    variations: ['Com travesseiro sob a cabeça', 'Com travesseiro sob os joelhos'],
  },
];

export const GROUP_ORDER = [
  'Posturas em pé',
  'Equilíbrio em pé',
  'Transição e força',
  'Flexões à frente',
  'Extensões',
  'Torções',
  'Abertura de quadris',
  'Recuperação',
  'Encerramento',
] as const;

export const getPoseById = (id: string): YogaPose | undefined => {
  return YOGA_POSES.find((pose) => pose.id === id);
};
